In [1]:
import pandas as pd

In [ ]:
#pandas has two core object series , dataframe

In [6]:
# series
import pandas as pd

s = pd.Series((1, 2, 2, 3), name="Age")

print(s)

0    1
1    2
2    2
3    3
Name: Age, dtype: int64

In [39]:
#datafram
#dict
import pandas as pd

# dictionary
di = {
    "name": ["anand", "mango", "pen", "mobile"],
    "identity": ["human", "fruit", "object", None]
}

# dataframe
df = pd.DataFrame(di)

print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [8]:
df.head(2)

    name identity
0  anand    human
1  mango    fruit

In [14]:
df.tail(2)

     name identity
2     pen   object
3  mobile     None

In [15]:
df.sample()

     name identity
3  mobile     None

In [40]:
df[["name", "identity"]]

     name identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     None

In [27]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [28]:
df

   count    name identity
0      1   anand    human
1     10   mango    fruit
2      3     pen   object
3      2  mobile     None

In [29]:
colour = "skin","orange","blue","black"

In [30]:
df["color"] =colour

In [32]:
df["id"]=[1,2,3,4]

In [33]:
df.sample()

   count name identity color  id
2      3  pen   object  blue   3

In [45]:
#new df df2 id , weight
import pandas as pd

df2 = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'weight': [55, 62, 48, 70, 60]
})

print(df2)

   id  weight
0   1      55
1   2      62
2   3      48
3   4      70
4   5      60

In [50]:
#merge and join
import pandas as pd

df = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "Name": ["Anand", "Mango", "Pen", "Mobile"]
})

df2 = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "weight": [55, 62, 48, 70, 60]
})

result = pd.merge(df, df2, how="right",on="id")
print(result)

   id    Name  weight
0   1   Anand      55
1   2   Mango      62
2   3     Pen      48
3   4  Mobile      70
4   5     NaN      60

In [51]:
result = pd.merge(df, df2, how="right",on="id")
print(result)

   id    Name  weight
0   1   Anand      55
1   2   Mango      62
2   3     Pen      48
3   4  Mobile      70
4   5     NaN      60