In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r"C:\Users\princi\Downloads\PBEL12\matches (1).csv ")

In [15]:
df.head(4)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,MI,NaN,6.0,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,RR,NaN,8.0,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,PBKS,NaN,3.0,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No

In [16]:
df.tail(2)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,KKR,NaN,NaN,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,RCB,NaN,9.0,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             39 non-null     int64
 1   date                 39 non-null     object
 2   venue                39 non-null     object
 3   team1                39 non-null     object
 4   team2                39 non-null     object
 5   stage                39 non-null     object
 6   toss_winner          39 non-null     object
 7   toss_decision        39 non-null     object
 8   first_ings_score     38 non-null     float64
 9   first_ings_wkts      38 non-null     float64
 10  second_ings_score    38 non-null     float64
 11  second_ings_wkts     38 non-null     float64
 12  match_result         39 non-null     object
 13  match_winner         38 non-null     object
 14  wb_runs              15 non-null     float64
 15  wb_wickets           22 non-null     float64
 16  balls_left           38 non-null     float64
 17  player_of_the_match  38 non-null     object
 18  top_scorer           38 non-null     object
 19  highscore            38 non-null     float64
 20  best_bowling         38 non-null     object
 21  best_bowling_figure  38 non-null     object
 22  super_over_match     39 non-null     object
dtypes: float64(8), int64(1), object(14)
memory usage: 7.1+ KB

In [18]:
df.isnull()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,True,True,True,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [ ]:
#find percentage of every col having null value

In [19]:
df["team1"].unique()
rcb=df["team1"]=="RCB"

In [20]:
df[rcb]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
10,11,"April 05, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,CSK,Bowl,250.0,3.0,...,RCB,43.0,NaN,2.0,Tim David,Tim David,70.0,Bhuvneshwar Kumar,3--41,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,RCB,NaN,5.0,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,DC,NaN,6.0,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,RCB,NaN,5.0,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No

In [22]:
nan = df["wb_runs"].isnull()
df[nan]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,MI,NaN,6.0,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,RR,NaN,8.0,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,PBKS,NaN,3.0,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,DC,NaN,6.0,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No
6,7,"April 03, 2026","MA Chidambaram Stadium, Chennai",CSK,PBKS,League,PBKS,Bowl,209.0,5.0,...,PBKS,NaN,5.0,8.0,Priyansh Arya,Ayush Matre,73.0,Vijaykumar Vyshak,2--38,No
7,8,"April 04, 2026","Arun Jaitley Stadium, Delhi",DC,MI,League,DC,Bowl,162.0,6.0,...,DC,NaN,6.0,11.0,Sameer Rizvi,Sameer Rizvi,90.0,Mukesh Kumar,2--26,No
9,10,"April 05, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,156.0,9.0,...,LSG,NaN,5.0,1.0,Mohammed Shami,Rishabh Pant,68.0,Mohammed Shami,2--9,No
11,12,"April 06, 2026","Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
14,15,"April 09, 2026","Eden Gardens, Kolkata",KKR,LSG,League,LSG,Bowl,181.0,4.0,...,LSG,NaN,3.0,0.0,Mukul Choudhary,Mukul Choudhary,54.0,Anukul Roy,2--32,No
15,16,"April 10, 2026","Barsapara Stadium, Guwahati",RR,RCB,League,RR,Bowl,201.0,8.0,...,RR,NaN,6.0,12.0,Vaibhav Sooryavanshi,Dhruv Jurel,81.0,Krunal Pandya,2--30,No
16,17,"April 11, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,SRH,League,PBKS,Bowl,219.0,6.0,...,PBKS,NaN,6.0,7.0,Shreyas Iyer,Abhishek Sharma,74.0,Shivang Kumar,3--33,No
18,19,"April 12, 2026","Ekana Cricket Stadium, Lucknow",LSG,GT,League,GT,Bowl,164.0,8.0,...,GT,NaN,7.0,8.0,Prasidh Krishna,Jos Buttler,60.0,Prasidh Krishna,4--28,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,RCB,NaN,5.0,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
23,24,"April 16, 2026","Wankhede Stadium, Mumbai",MI,PBKS,League,PBKS,Bowl,195.0,6.0,...,PBKS,NaN,7.0,21.0,Arshdeep Singh,Quinton de Kock,112.0,Arshdeep Singh,3--22,No
24,25,"April 17, 2026","Narendra Modi Stadium, Ahmedabad",GT,KKR,League,KKR,Bat,180.0,10.0,...,GT,NaN,5.0,2.0,Shubman Gill,Shubman Gill,86.0,Kagiso Rabada,3--29,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,DC,NaN,6.0,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
27,28,"April 19, 2026","Eden Gardens, Kolkata",KKR,RR,League,RR,Bat,155.0,9.0,...,KKR,NaN,4.0,2.0,Varun Chakravarthy,Rinku Singh,53.0,Varun Chakravarthy,3--14,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,RCB,NaN,5.0,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,PBKS,NaN,6.0,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,SRH,NaN,5.0,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,GT,NaN,8.0,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,KKR,NaN,NaN,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,RCB,NaN,9.0,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [23]:
df.drop(columns=["wb_runs","wb_wickets"])

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,4.0,completed,RCB,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,4.0,completed,MI,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,2.0,completed,RR,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,7.0,completed,PBKS,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,4.0,completed,DC,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No
5,6,"April 02, 2026","Eden Gardens, Kolkata",KKR,SRH,League,KKR,Bowl,226.0,8.0,...,10.0,completed,SRH,24.0,Nitish Kumar Reddy,Angkrish Raghuvanshi,52.0,Blessing Muzarabani,4--41,No
6,7,"April 03, 2026","MA Chidambaram Stadium, Chennai",CSK,PBKS,League,PBKS,Bowl,209.0,5.0,...,5.0,completed,PBKS,8.0,Priyansh Arya,Ayush Matre,73.0,Vijaykumar Vyshak,2--38,No
7,8,"April 04, 2026","Arun Jaitley Stadium, Delhi",DC,MI,League,DC,Bowl,162.0,6.0,...,4.0,completed,DC,11.0,Sameer Rizvi,Sameer Rizvi,90.0,Mukesh Kumar,2--26,No
8,9,"April 04, 2026","Narendra Modi Stadium, Ahmedabad",GT,RR,League,RR,Bat,210.0,6.0,...,8.0,completed,RR,0.0,Ravi Bishnoi,Dhruv Jurel,75.0,Ravi Bishnoi,4--41,No
9,10,"April 05, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,156.0,9.0,...,5.0,completed,LSG,1.0,Mohammed Shami,Rishabh Pant,68.0,Mohammed Shami,2--9,No
10,11,"April 05, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,CSK,Bowl,250.0,3.0,...,10.0,completed,RCB,2.0,Tim David,Tim David,70.0,Bhuvneshwar Kumar,3--41,No
11,12,"April 06, 2026","Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,abandoned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
12,13,"April 07, 2026","Barsapara Stadium, Guwahati",RR,MI,League,MI,Bowl,150.0,3.0,...,9.0,completed,RR,0.0,Yashasvi Jaiswal,Yashasvi Jaiswal,77.0,Sandeep Sharma,2--26,No
13,14,"April 08, 2026","Arun Jaitley Stadium, Delhi",DC,GT,League,DC,Bowl,210.0,4.0,...,8.0,completed,GT,0.0,Rashid Khan,KL Rahul,92.0,Rashid Khan,3--17,No
14,15,"April 09, 2026","Eden Gardens, Kolkata",KKR,LSG,League,LSG,Bowl,181.0,4.0,...,7.0,completed,LSG,0.0,Mukul Choudhary,Mukul Choudhary,54.0,Anukul Roy,2--32,No
15,16,"April 10, 2026","Barsapara Stadium, Guwahati",RR,RCB,League,RR,Bowl,201.0,8.0,...,4.0,completed,RR,12.0,Vaibhav Sooryavanshi,Dhruv Jurel,81.0,Krunal Pandya,2--30,No
16,17,"April 11, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,SRH,League,PBKS,Bowl,219.0,6.0,...,4.0,completed,PBKS,7.0,Shreyas Iyer,Abhishek Sharma,74.0,Shivang Kumar,3--33,No
17,18,"April 11, 2026","MA Chidambaram Stadium, Chennai",CSK,DC,League,DC,Bowl,212.0,2.0,...,10.0,completed,CSK,0.0,Sanju Samson,Sanju Samson,115.0,Jamie Overton,4--18,No
18,19,"April 12, 2026","Ekana Cricket Stadium, Lucknow",LSG,GT,League,GT,Bowl,164.0,8.0,...,3.0,completed,GT,8.0,Prasidh Krishna,Jos Buttler,60.0,Prasidh Krishna,4--28,No
19,20,"April 12, 2026","Wankhede Stadium, Mumbai",MI,RCB,League,MI,Bowl,240.0,4.0,...,5.0,completed,RCB,0.0,Phil Salt,Phil Salt,78.0,Suyash Sharma,2--47,No
20,21,"April 13, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,216.0,6.0,...,10.0,completed,SRH,6.0,Praful Hinge,Ishan Kishan,91.0,Sakib Hussain,4--24,No
21,22,"April 14, 2026","MA Chidambaram Stadium, Chennai",CSK,KKR,League,KKR,Bowl,192.0,5.0,...,7.0,completed,CSK,0.0,Noor Ahmad,Sanju Samson,48.0,Noor Ahmad,3--21,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,5.0,completed,RCB,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
23,24,"April 16, 2026","Wankhede Stadium, Mumbai",MI,PBKS,League,PBKS,Bowl,195.0,6.0,...,3.0,completed,PBKS,21.0,Arshdeep Singh,Quinton de Kock,112.0,Arshdeep Singh,3--22,No
24,25,"April 17, 2026","Narendra Modi Stadium, Ahmedabad",GT,KKR,League,KKR,Bat,180.0,10.0,...,5.0,completed,GT,2.0,Shubman Gill,Shubman Gill,86.0,Kagiso Rabada,3--29,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,4.0,completed,DC,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
26,27,"April 18, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,CSK,League,CSK,Bowl,194.0,9.0,...,8.0,completed,SRH,0.0,Eshan Malinga,Abhishek Sharma,59.0,Eshan Malinga,3--29,No
27,28,"April 19, 2026","Eden Gardens, Kolkata",KKR,RR,League,RR,Bat,155.0,9.0,...,6.0,completed,KKR,2.0,Varun Chakravarthy,Rinku Singh,53.0,Varun Chakravarthy,3--14,No
28,29,"April 19, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,LSG,League,LSG,Bowl,254.0,7.0,...,5.0,completed,PBKS,0.0,Priyansh Arya,Priyansh Arya,93.0,Prince Yadav,2--25,No
29,30,"April 20, 2026","Narendra Modi Stadium, Ahmedabad",GT,MI,League,GT,Bowl,199.0,5.0,...,10.0,completed,MI,25.0,Tilak Varma,Tilak Varma,101.0,Ashwani Kumar,4--24,No
30,31,"April 21, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,DC,League,DC,Bowl,242.0,2.0,...,9.0,completed,SRH,0.0,Abhishek Sharma,Abhishek Sharma,135.0,Eshan Malinga,4--32,No
31,32,"April 22, 2026","Ekana Cricket Stadium, Lucknow",LSG,RR,League,LSG,Bowl,159.0,6.0,...,10.0,completed,LSG,12.0,Ravindra Jadeja,Mitchell Marsh,55.0,Jofra Archer,3--20,No
32,33,"April 23, 2026","Wankhede Stadium, Mumbai",MI,CSK,League,MI,Bowl,207.0,6.0,...,10.0,completed,CSK,6.0,Sanju Samson,Sanju Samson,101.0,Akeal Hosein,4--17,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,5.0,completed,RCB,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,4.0,completed,PBKS,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,5.0,completed,SRH,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,2.0,completed,GT,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,8.0,completed,KKR,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,1.0,completed,RCB,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [24]:
nan=df["wb_runs"].isnull()
df[nan]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,MI,NaN,6.0,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,RR,NaN,8.0,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,PBKS,NaN,3.0,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,DC,NaN,6.0,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No
6,7,"April 03, 2026","MA Chidambaram Stadium, Chennai",CSK,PBKS,League,PBKS,Bowl,209.0,5.0,...,PBKS,NaN,5.0,8.0,Priyansh Arya,Ayush Matre,73.0,Vijaykumar Vyshak,2--38,No
7,8,"April 04, 2026","Arun Jaitley Stadium, Delhi",DC,MI,League,DC,Bowl,162.0,6.0,...,DC,NaN,6.0,11.0,Sameer Rizvi,Sameer Rizvi,90.0,Mukesh Kumar,2--26,No
9,10,"April 05, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,156.0,9.0,...,LSG,NaN,5.0,1.0,Mohammed Shami,Rishabh Pant,68.0,Mohammed Shami,2--9,No
11,12,"April 06, 2026","Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
14,15,"April 09, 2026","Eden Gardens, Kolkata",KKR,LSG,League,LSG,Bowl,181.0,4.0,...,LSG,NaN,3.0,0.0,Mukul Choudhary,Mukul Choudhary,54.0,Anukul Roy,2--32,No
15,16,"April 10, 2026","Barsapara Stadium, Guwahati",RR,RCB,League,RR,Bowl,201.0,8.0,...,RR,NaN,6.0,12.0,Vaibhav Sooryavanshi,Dhruv Jurel,81.0,Krunal Pandya,2--30,No
16,17,"April 11, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,SRH,League,PBKS,Bowl,219.0,6.0,...,PBKS,NaN,6.0,7.0,Shreyas Iyer,Abhishek Sharma,74.0,Shivang Kumar,3--33,No
18,19,"April 12, 2026","Ekana Cricket Stadium, Lucknow",LSG,GT,League,GT,Bowl,164.0,8.0,...,GT,NaN,7.0,8.0,Prasidh Krishna,Jos Buttler,60.0,Prasidh Krishna,4--28,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,RCB,NaN,5.0,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
23,24,"April 16, 2026","Wankhede Stadium, Mumbai",MI,PBKS,League,PBKS,Bowl,195.0,6.0,...,PBKS,NaN,7.0,21.0,Arshdeep Singh,Quinton de Kock,112.0,Arshdeep Singh,3--22,No
24,25,"April 17, 2026","Narendra Modi Stadium, Ahmedabad",GT,KKR,League,KKR,Bat,180.0,10.0,...,GT,NaN,5.0,2.0,Shubman Gill,Shubman Gill,86.0,Kagiso Rabada,3--29,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,DC,NaN,6.0,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
27,28,"April 19, 2026","Eden Gardens, Kolkata",KKR,RR,League,RR,Bat,155.0,9.0,...,KKR,NaN,4.0,2.0,Varun Chakravarthy,Rinku Singh,53.0,Varun Chakravarthy,3--14,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,RCB,NaN,5.0,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,PBKS,NaN,6.0,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,SRH,NaN,5.0,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,GT,NaN,8.0,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,KKR,NaN,NaN,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,RCB,NaN,9.0,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [25]:
df.isnull().sum

<bound method DataFrame.sum of     match_id   date  venue  team1  team2  stage  toss_winner  toss_decision  \
0      False  False  False  False  False  False        False          False
1      False  False  False  False  False  False        False          False
2      False  False  False  False  False  False        False          False
3      False  False  False  False  False  False        False          False
4      False  False  False  False  False  False        False          False
5      False  False  False  False  False  False        False          False
6      False  False  False  False  False  False        False          False
7      False  False  False  False  False  False        False          False
8      False  False  False  False  False  False        False          False
9      False  False  False  False  False  False        False          False
10     False  False  False  False  False  False        False          False
11     False  False  False  False  False  False        False          False
12     False  False  False  False  False  False        False          False
13     False  False  False  False  False  False        False          False
14     False  False  False  False  False  False        False          False
15     False  False  False  False  False  False        False          False
16     False  False  False  False  False  False        False          False
17     False  False  False  False  False  False        False          False
18     False  False  False  False  False  False        False          False
19     False  False  False  False  False  False        False          False
20     False  False  False  False  False  False        False          False
21     False  False  False  False  False  False        False          False
22     False  False  False  False  False  False        False          False
23     False  False  False  False  False  False        False          False
24     False  False  False  False  False  False        False          False
25     False  False  False  False  False  False        False          False
26     False  False  False  False  False  False        False          False
27     False  False  False  False  False  False        False          False
28     False  False  False  False  False  False        False          False
29     False  False  False  False  False  False        False          False
30     False  False  False  False  False  False        False          False
31     False  False  False  False  False  False        False          False
32     False  False  False  False  False  False        False          False
33     False  False  False  False  False  False        False          False
34     False  False  False  False  False  False        False          False
35     False  False  False  False  False  False        False          False
36     False  False  False  False  False  False        False          False
37     False  False  False  False  False  False        False          False
38     False  False  False  False  False  False        False          False

    first_ings_score  first_ings_wkts  ...  match_winner  wb_runs  wb_wickets  \
0              False            False  ...         False     True       False
1              False            False  ...         False     True       False
2              False            False  ...         False     True       False
3              False            False  ...         False     True       False
4              False            False  ...         False     True       False
5              False            False  ...         False    False        True
6              False            False  ...         False     True       False
7              False            False  ...         False     True       False
8              False            False  ...         False    False        True
9              False            False  ...         False     True       False
10             False            False  ...         False    False        True
11              True             True  ...          True     True        True
12             False            False  ...         False    False        True
13             False            False  ...         False    False        True
14             False            False  ...         False     True       False
15             False            False  ...         False     True       False
16             False            False  ...         False     True       False
17             False            False  ...         False    False        True
18             False            False  ...         False     True       False
19             False            False  ...         False    False        True
20             False            False  ...         False    False        True
21             False            False  ...         False    False        True
22             False            False  ...         False     True       False
23             False            False  ...         False     True       False
24             False            False  ...         False     True       False
25             False            False  ...         False     True       False
26             False            False  ...         False    False        True
27             False            False  ...         False     True       False
28             False            False  ...         False    False        True
29             False            False  ...         False    False        True
30             False            False  ...         False    False        True
31             False            False  ...         False    False        True
32             False            False  ...         False    False        True
33             False            False  ...         False     True       False
34             False            False  ...         False     True       False
35             False            False  ...         False     True       False
36             False            False  ...         False     True       False
37             False            False  ...         False     True        True
38             False            False  ...         False     True       False

    balls_left  player_of_the_match  top_scorer  highscore  best_bowling  \
0        False                False       False      False         False
1        False                False       False      False         False
2        False                False       False      False         False
3        False                False       False      False         False
4        False                False       False      False         False
5        False                False       False      False         False
6        False                False       False      False         False
7        False                False       False      False         False
8        False                False       False      False         False
9        False                False       False      False         False
10       False                False       False      False         False
11        True                 True        True       True          True
12       False                False       False      False         False
13       False                False       False      False         False
14       False                False       False      False         False
15       False                False       False      False         False
16       False                False       False      False         False
17       False                False       False      False         False
18       False                False       False      False         False
19       False                False       False      False         False
20       False                False       False      False         False
21       False                False       False      False         False
22       False                False       False      False         False
23       False                False       False      False         False
24       False                False       False      False         False
25       False                False       False      False         False
26       False                False       False      False         False
27       False                False       False      False         False
28       False                False       False      False         False
29       False                False       False      False         False
30       False                False       False      False         False
31       False                False       False      False         False
32       False                False       False      False         False
33       False                False       False      False         False
34       False                False       False      False         False
35       False                False       False      False         False
36       False                False       False      False         False
37       False                False       False      False         False
38       False                False       False      False         False

    best_bowling_figure  super_over_match
0                 False             False
1                 False             False
2                 False             False
3                 False             False
4                 False             False
5                 False             False
6                 False             False
7                 False             False
8                 False             False
9                 False             False
10                False             False
11                 True             False
12                False             False
13                False             False
14                False             False
15                False             False
16                False             False
17                False             False
18                False             False
19                False             False
20                False             False
21                False             False
22                False             False
23                False             False
24                False             False
25                False             False
26                False             False
27                False             False
28                False             False
29                False             False
30                False             False
31                False             False
32                False             False
33                False             False
34                False             False
35                False             False
36                False             False
37                False             False
38                False             False

[39 rows x 23 columns]>

In [36]:
df.columns

Index(['match_id', 'date', 'venue', 'team1', 'team2', 'stage', 'toss_winner',
       'toss_decision', 'first_ings_score', 'first_ings_wkts',
       'second_ings_score', 'second_ings_wkts', 'match_result', 'match_winner',
       'wb_runs', 'wb_wickets', 'balls_left', 'player_of_the_match',
       'top_scorer', 'highscore', 'best_bowling', 'best_bowling_figure',
       'super_over_match'],
      dtype='object')

In [37]:
df.columns[df.isnull().any()]

Index([], dtype='object')

In [38]:
df.columns[df.isnull().any(axis=1)]

C:\Users\princi\AppData\Local\Temp\ipykernel_13736\82369297.py:1: FutureWarning: Using a boolean indexer with length 0 on an Index with length greater than 0 is deprecated and will raise in a future version.
  df.columns[df.isnull().any(axis=1)]

Index([], dtype='object')

In [31]:
df=df.dropna()

In [33]:
df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_result           0
match_winner           0
wb_runs                0
wb_wickets             0
balls_left             0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
super_over_match       0
dtype: int64

In [34]:
df.fillna("missing")

Empty DataFrame
Columns: [match_id, date, venue, team1, team2, stage, toss_winner, toss_decision, first_ings_score, first_ings_wkts, second_ings_score, second_ings_wkts, match_result, match_winner, wb_runs, wb_wickets, balls_left, player_of_the_match, top_scorer, highscore, best_bowling, best_bowling_figure, super_over_match]
Index: []

[0 rows x 23 columns]

In [39]:
df['venue'].value_counts()

Series([], Name: count, dtype: int64)

In [40]:
df["match_winner"].value_counts()

Series([], Name: count, dtype: int64)

In [42]:
df.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,wb_runs,wb_wickets,balls_left,highscore
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#duplicate
#df.drop_suplicate()