In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\princi\Downloads\matches (2).csv")
print(df.head())

   match_id            date                               venue team1 team2  \
0         1  March 28, 2026   M. Chinnaswamy Stadium, Bangalore   RCB   SRH
1         2  March 29, 2026            Wankhede Stadium, Mumbai    MI   KKR
2         3  March 30, 2026         Barsapara Stadium, Guwahati    RR   CSK
3         4  March 31, 2026  New PCA Cricket Stadium, Mullanpur  PBKS    GT
4         5  April 01, 2026      Ekana Cricket Stadium, Lucknow   LSG    DC

    stage toss_winner toss_decision  first_ings_score  first_ings_wkts  ...  \
0  League         RCB          Bowl             201.0              9.0  ...
1  League          MI          Bowl             220.0              4.0  ...
2  League          RR          Bowl             127.0             10.0  ...
3  League        PBKS          Bowl             162.0              6.0  ...
4  League          DC          Bowl             141.0             10.0  ...

   match_winner  wb_runs wb_wickets balls_left  player_of_the_match  \
0           RCB      NaN        6.0       26.0          Jacob Duffy
1            MI      NaN        6.0        5.0       Shardul Thakur
2            RR      NaN        8.0       47.0        Nandre Burger
3          PBKS      NaN        3.0        5.0      Cooper Connolly
4            DC      NaN        6.0       17.0         Sameer Rizvi

             top_scorer  highscore     best_bowling best_bowling_figure  \
0          Ishan Kishan       80.0      Jacob Duffy               3--22
1        Ryan Rickelton       81.0   Shardul Thakur               3--39
2  Vaibhav Sooryavanshi       52.0     Jofra Archer               2--19
3       Cooper Connolly       72.0  Prasidh Krishna               3--29
4          Sameer Rizvi       70.0      Lungi Ngidi               3--27

   super_over_match
0                No
1                No
2                No
3                No
4                No

[5 rows x 23 columns]

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             39 non-null     int64
 1   date                 39 non-null     object
 2   venue                39 non-null     object
 3   team1                39 non-null     object
 4   team2                39 non-null     object
 5   stage                39 non-null     object
 6   toss_winner          39 non-null     object
 7   toss_decision        39 non-null     object
 8   first_ings_score     38 non-null     float64
 9   first_ings_wkts      38 non-null     float64
 10  second_ings_score    38 non-null     float64
 11  second_ings_wkts     38 non-null     float64
 12  match_result         39 non-null     object
 13  match_winner         38 non-null     object
 14  wb_runs              15 non-null     float64
 15  wb_wickets           22 non-null     float64
 16  balls_left           38 non-null     float64
 17  player_of_the_match  38 non-null     object
 18  top_scorer           38 non-null     object
 19  highscore            38 non-null     float64
 20  best_bowling         38 non-null     object
 21  best_bowling_figure  38 non-null     object
 22  super_over_match     39 non-null     object
dtypes: float64(8), int64(1), object(14)
memory usage: 7.1+ KB
None

In [7]:
df.isnull()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,True,True,True,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

In [9]:
df.isnull().sum()/len(df)*100

match_id                0.000000
date                    0.000000
venue                   0.000000
team1                   0.000000
team2                   0.000000
stage                   0.000000
toss_winner             0.000000
toss_decision           0.000000
first_ings_score        2.564103
first_ings_wkts         2.564103
second_ings_score       2.564103
second_ings_wkts        2.564103
match_result            0.000000
match_winner            2.564103
wb_runs                61.538462
wb_wickets             43.589744
balls_left              2.564103
player_of_the_match     2.564103
top_scorer              2.564103
highscore               2.564103
best_bowling            2.564103
best_bowling_figure     2.564103
super_over_match        0.000000
dtype: float64

In [10]:
df["team1"].unique

<bound method Series.unique of 0      RCB
1       MI
2       RR
3     PBKS
4      LSG
5      KKR
6      CSK
7       DC
8       GT
9      SRH
10     RCB
11     KKR
12      RR
13      DC
14     KKR
15      RR
16    PBKS
17     CSK
18     LSG
19      MI
20     SRH
21     CSK
22     RCB
23      MI
24      GT
25     RCB
26     SRH
27     KKR
28    PBKS
29      GT
30     SRH
31     LSG
32      MI
33     RCB
34      DC
35      RR
36      GT
37     LSG
38      DC
Name: team1, dtype: object>

In [11]:
df["team1"].unique()
rcb=df["team1"]

In [12]:
df=df.drop(columns=["wb_runs",'wb_wickets'])

In [13]:
df[df.isnull().any(axis=1)]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
11,12,"April 06, 2026","Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,abandoned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No

In [14]:
df=df.dropna()

In [15]:
df

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,4.0,completed,RCB,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,4.0,completed,MI,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,2.0,completed,RR,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,7.0,completed,PBKS,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,4.0,completed,DC,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No
5,6,"April 02, 2026","Eden Gardens, Kolkata",KKR,SRH,League,KKR,Bowl,226.0,8.0,...,10.0,completed,SRH,24.0,Nitish Kumar Reddy,Angkrish Raghuvanshi,52.0,Blessing Muzarabani,4--41,No
6,7,"April 03, 2026","MA Chidambaram Stadium, Chennai",CSK,PBKS,League,PBKS,Bowl,209.0,5.0,...,5.0,completed,PBKS,8.0,Priyansh Arya,Ayush Matre,73.0,Vijaykumar Vyshak,2--38,No
7,8,"April 04, 2026","Arun Jaitley Stadium, Delhi",DC,MI,League,DC,Bowl,162.0,6.0,...,4.0,completed,DC,11.0,Sameer Rizvi,Sameer Rizvi,90.0,Mukesh Kumar,2--26,No
8,9,"April 04, 2026","Narendra Modi Stadium, Ahmedabad",GT,RR,League,RR,Bat,210.0,6.0,...,8.0,completed,RR,0.0,Ravi Bishnoi,Dhruv Jurel,75.0,Ravi Bishnoi,4--41,No
9,10,"April 05, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,156.0,9.0,...,5.0,completed,LSG,1.0,Mohammed Shami,Rishabh Pant,68.0,Mohammed Shami,2--9,No
10,11,"April 05, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,CSK,Bowl,250.0,3.0,...,10.0,completed,RCB,2.0,Tim David,Tim David,70.0,Bhuvneshwar Kumar,3--41,No
12,13,"April 07, 2026","Barsapara Stadium, Guwahati",RR,MI,League,MI,Bowl,150.0,3.0,...,9.0,completed,RR,0.0,Yashasvi Jaiswal,Yashasvi Jaiswal,77.0,Sandeep Sharma,2--26,No
13,14,"April 08, 2026","Arun Jaitley Stadium, Delhi",DC,GT,League,DC,Bowl,210.0,4.0,...,8.0,completed,GT,0.0,Rashid Khan,KL Rahul,92.0,Rashid Khan,3--17,No
14,15,"April 09, 2026","Eden Gardens, Kolkata",KKR,LSG,League,LSG,Bowl,181.0,4.0,...,7.0,completed,LSG,0.0,Mukul Choudhary,Mukul Choudhary,54.0,Anukul Roy,2--32,No
15,16,"April 10, 2026","Barsapara Stadium, Guwahati",RR,RCB,League,RR,Bowl,201.0,8.0,...,4.0,completed,RR,12.0,Vaibhav Sooryavanshi,Dhruv Jurel,81.0,Krunal Pandya,2--30,No
16,17,"April 11, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,SRH,League,PBKS,Bowl,219.0,6.0,...,4.0,completed,PBKS,7.0,Shreyas Iyer,Abhishek Sharma,74.0,Shivang Kumar,3--33,No
17,18,"April 11, 2026","MA Chidambaram Stadium, Chennai",CSK,DC,League,DC,Bowl,212.0,2.0,...,10.0,completed,CSK,0.0,Sanju Samson,Sanju Samson,115.0,Jamie Overton,4--18,No
18,19,"April 12, 2026","Ekana Cricket Stadium, Lucknow",LSG,GT,League,GT,Bowl,164.0,8.0,...,3.0,completed,GT,8.0,Prasidh Krishna,Jos Buttler,60.0,Prasidh Krishna,4--28,No
19,20,"April 12, 2026","Wankhede Stadium, Mumbai",MI,RCB,League,MI,Bowl,240.0,4.0,...,5.0,completed,RCB,0.0,Phil Salt,Phil Salt,78.0,Suyash Sharma,2--47,No
20,21,"April 13, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,216.0,6.0,...,10.0,completed,SRH,6.0,Praful Hinge,Ishan Kishan,91.0,Sakib Hussain,4--24,No
21,22,"April 14, 2026","MA Chidambaram Stadium, Chennai",CSK,KKR,League,KKR,Bowl,192.0,5.0,...,7.0,completed,CSK,0.0,Noor Ahmad,Sanju Samson,48.0,Noor Ahmad,3--21,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,5.0,completed,RCB,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
23,24,"April 16, 2026","Wankhede Stadium, Mumbai",MI,PBKS,League,PBKS,Bowl,195.0,6.0,...,3.0,completed,PBKS,21.0,Arshdeep Singh,Quinton de Kock,112.0,Arshdeep Singh,3--22,No
24,25,"April 17, 2026","Narendra Modi Stadium, Ahmedabad",GT,KKR,League,KKR,Bat,180.0,10.0,...,5.0,completed,GT,2.0,Shubman Gill,Shubman Gill,86.0,Kagiso Rabada,3--29,No
25,26,"April 18, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,DC,League,DC,Bowl,175.0,8.0,...,4.0,completed,DC,1.0,Tristan Stubbs,Phil Salt,63.0,Bhuvneshwar Kumar,3--26,No
26,27,"April 18, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,CSK,League,CSK,Bowl,194.0,9.0,...,8.0,completed,SRH,0.0,Eshan Malinga,Abhishek Sharma,59.0,Eshan Malinga,3--29,No
27,28,"April 19, 2026","Eden Gardens, Kolkata",KKR,RR,League,RR,Bat,155.0,9.0,...,6.0,completed,KKR,2.0,Varun Chakravarthy,Rinku Singh,53.0,Varun Chakravarthy,3--14,No
28,29,"April 19, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,LSG,League,LSG,Bowl,254.0,7.0,...,5.0,completed,PBKS,0.0,Priyansh Arya,Priyansh Arya,93.0,Prince Yadav,2--25,No
29,30,"April 20, 2026","Narendra Modi Stadium, Ahmedabad",GT,MI,League,GT,Bowl,199.0,5.0,...,10.0,completed,MI,25.0,Tilak Varma,Tilak Varma,101.0,Ashwani Kumar,4--24,No
30,31,"April 21, 2026","Rajiv Gandhi International Stadium, Hyderabad",SRH,DC,League,DC,Bowl,242.0,2.0,...,9.0,completed,SRH,0.0,Abhishek Sharma,Abhishek Sharma,135.0,Eshan Malinga,4--32,No
31,32,"April 22, 2026","Ekana Cricket Stadium, Lucknow",LSG,RR,League,LSG,Bowl,159.0,6.0,...,10.0,completed,LSG,12.0,Ravindra Jadeja,Mitchell Marsh,55.0,Jofra Archer,3--20,No
32,33,"April 23, 2026","Wankhede Stadium, Mumbai",MI,CSK,League,MI,Bowl,207.0,6.0,...,10.0,completed,CSK,6.0,Sanju Samson,Sanju Samson,101.0,Akeal Hosein,4--17,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,5.0,completed,RCB,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,4.0,completed,PBKS,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,5.0,completed,SRH,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,2.0,completed,GT,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,8.0,completed,KKR,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,1.0,completed,RCB,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [16]:
df.isnull().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_result           0
match_winner           0
balls_left             0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
super_over_match       0
dtype: int64

In [17]:
df.columns

Index(['match_id', 'date', 'venue', 'team1', 'team2', 'stage', 'toss_winner',
       'toss_decision', 'first_ings_score', 'first_ings_wkts',
       'second_ings_score', 'second_ings_wkts', 'match_result', 'match_winner',
       'balls_left', 'player_of_the_match', 'top_scorer', 'highscore',
       'best_bowling', 'best_bowling_figure', 'super_over_match'],
      dtype='object')

In [18]:
df['venue'].value_counts()

venue
M. Chinnaswamy Stadium, Bangalore                5
Wankhede Stadium, Mumbai                         4
Ekana Cricket Stadium, Lucknow                   4
Narendra Modi Stadium, Ahmedabad                 4
Rajiv Gandhi International Stadium, Hyderabad    4
Arun Jaitley Stadium, Delhi                      4
Barsapara Stadium, Guwahati                      3
MA Chidambaram Stadium, Chennai                  3
Eden Gardens, Kolkata                            3
New PCA Cricket Stadium, Mullanpur               3
Sawai Mansingh Stadium, Jaipur                   1
Name: count, dtype: int64

In [19]:
df['match_winner'].value_counts()

match_winner
RCB     6
PBKS    6
SRH     5
RR      4
GT      4
DC      3
CSK     3
LSG     3
MI      2
KKR     2
Name: count, dtype: int64

In [20]:
df.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,balls_left,highscore
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,20.210526,190.526316,6.289474,175.500000,6.052632,10.684211,79.447368
std,11.477729,39.394565,2.470451,39.747684,2.670635,15.773918,24.521031
min,1.000000,75.000000,2.000000,77.000000,1.000000,0.000000,34.000000
25%,10.250000,159.750000,4.250000,159.250000,4.000000,0.250000,60.750000
50%,20.500000,197.000000,6.000000,180.000000,5.000000,6.000000,77.500000
75%,29.750000,215.000000,8.000000,203.750000,8.000000,12.000000,91.750000
max,39.000000,264.000000,10.000000,265.000000,10.000000,81.000000,152.000000